### ISSUE TITLE
Result didnt same as expected

### ISSUE THREAD

**Issue by budimm** [josiahdahl/docker-reverse-proxy-example#6]
I'am using ubuntu 18.04, and do all readme need to do..

My result when i run : 

`curl site1.docker-proxy.dev:8080` or other command..

```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
```

Is I need add some configuration ?
Thanks for reply..

**Comment by josiahdahl** [comment]
.dev is now a top level domain - I suggest changing it to .localhost or .test. I'll update the repo.

**Comment by budimm** [comment]
Thanks for fast reply,, 
Ok, i'll wait the update..
Trims..

**Comment by josiahdahl** [comment]
@budim12 The two issues you reported have been resolved.

**Comment by budimm** [comment]
Okay, thanks,,
Just some note / add ons ..
```
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.15.9</center>
</body>
</html>
```

If that occur, probabbly cz file permission,, ok, that's it..
:+1:
